---
- hosts: all
  gather_facts: no
  become: true
  vars:
    wrkdir: /etc/sf

  tasks:
  # Create a directory and copy files
  - name: Create a working directory
    ansible.builtin.file:
      path: "{{ wrkdir }}"
      state: directory
      mode: "777"

  - name: Copy files for a docker image
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ wrkdir }}"
    loop:
      - requirements.txt
      - web.conf
      - web.py
      - Dockerfile

  # Install Docker
  - name: Install Docker dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
      update_cache: true
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent

  - name: Add Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    ansible.builtin.apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Start docker
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

  # Create and run containers
  - name: Create a bridge network to connect containers
    shell:
      cmd: "docker network create --subnet=172.18.0.0/16 {{ db_net }}"
      chdir: "{{ wrkdir }}"

  - name: Create and run a postgres container with a database and user
    shell:
      cmd: "docker run -d --name web-postgres --net {{ db_net }} --ip {{ dp_static_ip }} -p 5432:5432 -e POSTGRES_DB={{ db_name }} -e POSTGRES_USER={{ db_user }} -e POSTGRES_PASSWORD={{ db_password }} postgres"
      chdir: "{{ wrkdir }}"

  - name: Create a docker image for a web app
    shell:
      cmd: "docker build -t web ."
      chdir: "{{ wrkdir }}"
  
  - name: Create and run a web app container
    shell:
      cmd: "docker run --detach -p 80:5000 --net {{ db_net }} --name web-flask web:latest"
      chdir: "{{ wrkdir }}"
